# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rcheiko <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/07 17:23:09 by rcheiko           #+#    #+#              #
#    Updated: 2022/03/23 11:27:03 by rcheiko          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3"
services:
    nginx:
        container_name: nginx
        build: requirements/nginx/
        ports:
            - "443:443"
        depends_on:
            - "php-wordpress"
        volumes:
            - phpvolume:/var/www/html
        networks:
           - host
        restart: always
    php-wordpress:
        container_name: wordpress
        build: requirements/wordpress/
        ports:
            - "9000:9000"
        depends_on:
            - "mariadb"
        volumes: 
            - phpvolume:/var/www/html
        networks:
            - host
        restart: always
    mariadb:
        container_name: mariadb
        build: requirements/mariadb/
        ports:
            - "3306:3306"
        volumes:
            - mariadbvolume:/var/lib/mysql
        networks:
            - host
        environment:
            MYSQL_DATABASE: 'wordpress'
            MYSQL_USER: 'wpuser'
            MYSQL_PASSWORD: 'password'
        restart: always
volumes:
    phpvolume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: 'home/rcheiko/data/wordpress/'
    mariadbvolume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: 'home/rcheiko/data/mariadb/'
networks:
    host:
