# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rcheiko <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/07 17:23:09 by rcheiko           #+#    #+#              #
#    Updated: 2022/03/07 18:04:08 by rcheiko          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
    web:
        image: nginx
        volume: nginx/
        ports:
            - "8080:80"
    
